import type { Event } from "@/types";

export const MOCK_EVENTS: Event[] = [
  {
    id: "7",
    title: "Detty December Kickoff Party",
    description: "Lagos's most anticipated end-of-year rave. DJ sets, live performances, open bar, and vibes that go all night.",
    banner_url: "",
    category: "Party & Rave",
    venue: "Landmark Beach",
    city: "Lagos",
    date: "2026-12-05",
    time: "21:00",
    organizer_name: "Rave Republic NG",
    min_price: 15000,
    max_price: 80000,
    is_free: false,
    status: "published",
  },
  {
    id: "1",
    title: "Afro Nation Lagos 2026",
    description:
      "The biggest Afrobeats festival returns to Lagos with three days of unforgettable performances from your favourite artists across Africa and beyond.",
    banner_url: "",
    category: "Music",
    venue: "Eko Atlantic City",
    city: "Lagos",
    date: "2026-07-18",
    time: "16:00",
    organizer_name: "Afro Nation",
    min_price: 25000,
    max_price: 150000,
    is_free: false,
    status: "published",
  },
  {
    id: "2",
    title: "Lagos Tech Summit",
    description:
      "Join 5,000+ founders, engineers, and investors shaping the future of African tech. Keynotes, workshops, and demo nights.",
    banner_url: "",
    category: "Tech & Business",
    venue: "Landmark Event Centre",
    city: "Lagos",
    date: "2026-09-12",
    time: "09:00",
    organizer_name: "Lagos Tech Council",
    min_price: 15000,
    max_price: 75000,
    is_free: false,
    status: "published",
  },
  {
    id: "3",
    title: "Abuja Food & Wine Festival",
    description:
      "A weekend celebration of Nigerian cuisine, wine tastings, and live cooking demos with celebrity chefs.",
    banner_url: "",
    category: "Food & Drink",
    venue: "Transcorp Hilton Gardens",
    city: "Abuja",
    date: "2026-08-22",
    time: "12:00",
    organizer_name: "Taste Naija",
    min_price: 0,
    max_price: 0,
    is_free: true,
    status: "published",
  },
  {
    id: "4",
    title: "Burna Boy: Live in Lagos",
    description:
      "The African Giant returns home for one electrifying night at the Tafawa Balewa Square.",
    banner_url: "",
    category: "Music",
    venue: "Tafawa Balewa Square",
    city: "Lagos",
    date: "2026-12-21",
    time: "20:00",
    organizer_name: "Spaceship Entertainment",
    min_price: 10000,
    max_price: 250000,
    is_free: false,
    status: "published",
  },
  {
    id: "5",
    title: "Founders Brunch Abuja",
    description:
      "An intimate brunch experience connecting Nigeria's next generation of founders and operators.",
    banner_url: "",
    category: "Tech & Business",
    venue: "The Wells Carlton",
    city: "Abuja",
    date: "2026-06-29",
    time: "11:00",
    organizer_name: "Founders Circle NG",
    min_price: 20000,
    max_price: 35000,
    is_free: false,
    status: "published",
  },
  {
    id: "6",
    title: "Jollof Wars: The Cookoff",
    description:
      "Twelve chefs. One pot of glory. Come taste, vote, and crown the king of Jollof for 2026.",
    banner_url: "",
    category: "Food & Drink",
    venue: "Muri Okunola Park",
    city: "Lagos",
    date: "2026-10-05",
    time: "13:00",
    organizer_name: "Chop Life NG",
    min_price: 5000,
    max_price: 12000,
    is_free: false,
    status: "published",
  },
];
