/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PaymentCallbackRouteImport } from './routes/payment-callback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as OrganisersUsernameRouteImport } from './routes/organisers.$username'
import { Route as OrderConfirmationOrderIdRouteImport } from './routes/order-confirmation.$orderId'
import { Route as DashboardOrganiserRouteImport } from './routes/dashboard.organiser'
import { Route as DashboardAttendeeRouteImport } from './routes/dashboard.attendee'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as EventsSlugIndexRouteImport } from './routes/events.$slug.index'
import { Route as DashboardOrganiserIndexRouteImport } from './routes/dashboard.organiser.index'
import { Route as DashboardAttendeeIndexRouteImport } from './routes/dashboard.attendee.index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as EventsSlugCheckoutRouteImport } from './routes/events.$slug.checkout'
import { Route as DashboardOrganiserTicketsRouteImport } from './routes/dashboard.organiser.tickets'
import { Route as DashboardOrganiserSettingsRouteImport } from './routes/dashboard.organiser.settings'
import { Route as DashboardOrganiserSalesRouteImport } from './routes/dashboard.organiser.sales'
import { Route as DashboardOrganiserEventsRouteImport } from './routes/dashboard.organiser.events'
import { Route as DashboardOrganiserCreateEventRouteImport } from './routes/dashboard.organiser.create-event'
import { Route as DashboardAttendeeTicketsRouteImport } from './routes/dashboard.attendee.tickets'
import { Route as DashboardAttendeeSettingsRouteImport } from './routes/dashboard.attendee.settings'
import { Route as DashboardAttendeeSavedRouteImport } from './routes/dashboard.attendee.saved'
import { Route as DashboardAdminTicketsRouteImport } from './routes/dashboard.admin.tickets'
import { Route as DashboardOrganiserScanEventIdRouteImport } from './routes/dashboard.organiser.scan.$eventId'
import { Route as DashboardOrganiserEditEventEventIdRouteImport } from './routes/dashboard.organiser.edit-event.$eventId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment-callback',
  path: '/payment-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const OrganisersUsernameRoute = OrganisersUsernameRouteImport.update({
  id: '/organisers/$username',
  path: '/organisers/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationOrderIdRoute =
  OrderConfirmationOrderIdRouteImport.update({
    id: '/order-confirmation/$orderId',
    path: '/order-confirmation/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardOrganiserRoute = DashboardOrganiserRouteImport.update({
  id: '/organiser',
  path: '/organiser',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAttendeeRoute = DashboardAttendeeRouteImport.update({
  id: '/attendee',
  path: '/attendee',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const EventsSlugIndexRoute = EventsSlugIndexRouteImport.update({
  id: '/events/$slug/',
  path: '/events/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrganiserIndexRoute = DashboardOrganiserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardOrganiserRoute,
} as any)
const DashboardAttendeeIndexRoute = DashboardAttendeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAttendeeRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const EventsSlugCheckoutRoute = EventsSlugCheckoutRouteImport.update({
  id: '/events/$slug/checkout',
  path: '/events/$slug/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrganiserTicketsRoute =
  DashboardOrganiserTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => DashboardOrganiserRoute,
  } as any)
const DashboardOrganiserSettingsRoute =
  DashboardOrganiserSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardOrganiserRoute,
  } as any)
const DashboardOrganiserSalesRoute = DashboardOrganiserSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => DashboardOrganiserRoute,
} as any)
const DashboardOrganiserEventsRoute =
  DashboardOrganiserEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => DashboardOrganiserRoute,
  } as any)
const DashboardOrganiserCreateEventRoute =
  DashboardOrganiserCreateEventRouteImport.update({
    id: '/create-event',
    path: '/create-event',
    getParentRoute: () => DashboardOrganiserRoute,
  } as any)
const DashboardAttendeeTicketsRoute =
  DashboardAttendeeTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => DashboardAttendeeRoute,
  } as any)
const DashboardAttendeeSettingsRoute =
  DashboardAttendeeSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardAttendeeRoute,
  } as any)
const DashboardAttendeeSavedRoute = DashboardAttendeeSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => DashboardAttendeeRoute,
} as any)
const DashboardAdminTicketsRoute = DashboardAdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardOrganiserScanEventIdRoute =
  DashboardOrganiserScanEventIdRouteImport.update({
    id: '/scan/$eventId',
    path: '/scan/$eventId',
    getParentRoute: () => DashboardOrganiserRoute,
  } as any)
const DashboardOrganiserEditEventEventIdRoute =
  DashboardOrganiserEditEventEventIdRouteImport.update({
    id: '/edit-event/$eventId',
    path: '/edit-event/$eventId',
    getParentRoute: () => DashboardOrganiserRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/payment-callback': typeof PaymentCallbackRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/attendee': typeof DashboardAttendeeRouteWithChildren
  '/dashboard/organiser': typeof DashboardOrganiserRouteWithChildren
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/organisers/$username': typeof OrganisersUsernameRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/dashboard/admin/tickets': typeof DashboardAdminTicketsRoute
  '/dashboard/attendee/saved': typeof DashboardAttendeeSavedRoute
  '/dashboard/attendee/settings': typeof DashboardAttendeeSettingsRoute
  '/dashboard/attendee/tickets': typeof DashboardAttendeeTicketsRoute
  '/dashboard/organiser/create-event': typeof DashboardOrganiserCreateEventRoute
  '/dashboard/organiser/events': typeof DashboardOrganiserEventsRoute
  '/dashboard/organiser/sales': typeof DashboardOrganiserSalesRoute
  '/dashboard/organiser/settings': typeof DashboardOrganiserSettingsRoute
  '/dashboard/organiser/tickets': typeof DashboardOrganiserTicketsRoute
  '/events/$slug/checkout': typeof EventsSlugCheckoutRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/attendee/': typeof DashboardAttendeeIndexRoute
  '/dashboard/organiser/': typeof DashboardOrganiserIndexRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
  '/dashboard/organiser/edit-event/$eventId': typeof DashboardOrganiserEditEventEventIdRoute
  '/dashboard/organiser/scan/$eventId': typeof DashboardOrganiserScanEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/payment-callback': typeof PaymentCallbackRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/organisers/$username': typeof OrganisersUsernameRoute
  '/dashboard': typeof DashboardIndexRoute
  '/events': typeof EventsIndexRoute
  '/dashboard/admin/tickets': typeof DashboardAdminTicketsRoute
  '/dashboard/attendee/saved': typeof DashboardAttendeeSavedRoute
  '/dashboard/attendee/settings': typeof DashboardAttendeeSettingsRoute
  '/dashboard/attendee/tickets': typeof DashboardAttendeeTicketsRoute
  '/dashboard/organiser/create-event': typeof DashboardOrganiserCreateEventRoute
  '/dashboard/organiser/events': typeof DashboardOrganiserEventsRoute
  '/dashboard/organiser/sales': typeof DashboardOrganiserSalesRoute
  '/dashboard/organiser/settings': typeof DashboardOrganiserSettingsRoute
  '/dashboard/organiser/tickets': typeof DashboardOrganiserTicketsRoute
  '/events/$slug/checkout': typeof EventsSlugCheckoutRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/attendee': typeof DashboardAttendeeIndexRoute
  '/dashboard/organiser': typeof DashboardOrganiserIndexRoute
  '/events/$slug': typeof EventsSlugIndexRoute
  '/dashboard/organiser/edit-event/$eventId': typeof DashboardOrganiserEditEventEventIdRoute
  '/dashboard/organiser/scan/$eventId': typeof DashboardOrganiserScanEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/payment-callback': typeof PaymentCallbackRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/attendee': typeof DashboardAttendeeRouteWithChildren
  '/dashboard/organiser': typeof DashboardOrganiserRouteWithChildren
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/organisers/$username': typeof OrganisersUsernameRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/dashboard/admin/tickets': typeof DashboardAdminTicketsRoute
  '/dashboard/attendee/saved': typeof DashboardAttendeeSavedRoute
  '/dashboard/attendee/settings': typeof DashboardAttendeeSettingsRoute
  '/dashboard/attendee/tickets': typeof DashboardAttendeeTicketsRoute
  '/dashboard/organiser/create-event': typeof DashboardOrganiserCreateEventRoute
  '/dashboard/organiser/events': typeof DashboardOrganiserEventsRoute
  '/dashboard/organiser/sales': typeof DashboardOrganiserSalesRoute
  '/dashboard/organiser/settings': typeof DashboardOrganiserSettingsRoute
  '/dashboard/organiser/tickets': typeof DashboardOrganiserTicketsRoute
  '/events/$slug/checkout': typeof EventsSlugCheckoutRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/attendee/': typeof DashboardAttendeeIndexRoute
  '/dashboard/organiser/': typeof DashboardOrganiserIndexRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
  '/dashboard/organiser/edit-event/$eventId': typeof DashboardOrganiserEditEventEventIdRoute
  '/dashboard/organiser/scan/$eventId': typeof DashboardOrganiserScanEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/payment-callback'
    | '/reset-password'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/attendee'
    | '/dashboard/organiser'
    | '/order-confirmation/$orderId'
    | '/organisers/$username'
    | '/dashboard/'
    | '/events/'
    | '/dashboard/admin/tickets'
    | '/dashboard/attendee/saved'
    | '/dashboard/attendee/settings'
    | '/dashboard/attendee/tickets'
    | '/dashboard/organiser/create-event'
    | '/dashboard/organiser/events'
    | '/dashboard/organiser/sales'
    | '/dashboard/organiser/settings'
    | '/dashboard/organiser/tickets'
    | '/events/$slug/checkout'
    | '/dashboard/admin/'
    | '/dashboard/attendee/'
    | '/dashboard/organiser/'
    | '/events/$slug/'
    | '/dashboard/organiser/edit-event/$eventId'
    | '/dashboard/organiser/scan/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/payment-callback'
    | '/reset-password'
    | '/signup'
    | '/order-confirmation/$orderId'
    | '/organisers/$username'
    | '/dashboard'
    | '/events'
    | '/dashboard/admin/tickets'
    | '/dashboard/attendee/saved'
    | '/dashboard/attendee/settings'
    | '/dashboard/attendee/tickets'
    | '/dashboard/organiser/create-event'
    | '/dashboard/organiser/events'
    | '/dashboard/organiser/sales'
    | '/dashboard/organiser/settings'
    | '/dashboard/organiser/tickets'
    | '/events/$slug/checkout'
    | '/dashboard/admin'
    | '/dashboard/attendee'
    | '/dashboard/organiser'
    | '/events/$slug'
    | '/dashboard/organiser/edit-event/$eventId'
    | '/dashboard/organiser/scan/$eventId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/payment-callback'
    | '/reset-password'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/attendee'
    | '/dashboard/organiser'
    | '/order-confirmation/$orderId'
    | '/organisers/$username'
    | '/dashboard/'
    | '/events/'
    | '/dashboard/admin/tickets'
    | '/dashboard/attendee/saved'
    | '/dashboard/attendee/settings'
    | '/dashboard/attendee/tickets'
    | '/dashboard/organiser/create-event'
    | '/dashboard/organiser/events'
    | '/dashboard/organiser/sales'
    | '/dashboard/organiser/settings'
    | '/dashboard/organiser/tickets'
    | '/events/$slug/checkout'
    | '/dashboard/admin/'
    | '/dashboard/attendee/'
    | '/dashboard/organiser/'
    | '/events/$slug/'
    | '/dashboard/organiser/edit-event/$eventId'
    | '/dashboard/organiser/scan/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  OrderConfirmationOrderIdRoute: typeof OrderConfirmationOrderIdRoute
  OrganisersUsernameRoute: typeof OrganisersUsernameRoute
  EventsIndexRoute: typeof EventsIndexRoute
  EventsSlugCheckoutRoute: typeof EventsSlugCheckoutRoute
  EventsSlugIndexRoute: typeof EventsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-callback': {
      id: '/payment-callback'
      path: '/payment-callback'
      fullPath: '/payment-callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/organisers/$username': {
      id: '/organisers/$username'
      path: '/organisers/$username'
      fullPath: '/organisers/$username'
      preLoaderRoute: typeof OrganisersUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation/$orderId': {
      id: '/order-confirmation/$orderId'
      path: '/order-confirmation/$orderId'
      fullPath: '/order-confirmation/$orderId'
      preLoaderRoute: typeof OrderConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/organiser': {
      id: '/dashboard/organiser'
      path: '/organiser'
      fullPath: '/dashboard/organiser'
      preLoaderRoute: typeof DashboardOrganiserRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/attendee': {
      id: '/dashboard/attendee'
      path: '/attendee'
      fullPath: '/dashboard/attendee'
      preLoaderRoute: typeof DashboardAttendeeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/events/$slug/': {
      id: '/events/$slug/'
      path: '/events/$slug'
      fullPath: '/events/$slug/'
      preLoaderRoute: typeof EventsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/organiser/': {
      id: '/dashboard/organiser/'
      path: '/'
      fullPath: '/dashboard/organiser/'
      preLoaderRoute: typeof DashboardOrganiserIndexRouteImport
      parentRoute: typeof DashboardOrganiserRoute
    }
    '/dashboard/attendee/': {
      id: '/dashboard/attendee/'
      path: '/'
      fullPath: '/dashboard/attendee/'
      preLoaderRoute: typeof DashboardAttendeeIndexRouteImport
      parentRoute: typeof DashboardAttendeeRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/events/$slug/checkout': {
      id: '/events/$slug/checkout'
      path: '/events/$slug/checkout'
      fullPath: '/events/$slug/checkout'
      preLoaderRoute: typeof EventsSlugCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/organiser/tickets': {
      id: '/dashboard/organiser/tickets'
      path: '/tickets'
      fullPath: '/dashboard/organiser/tickets'
      preLoaderRoute: typeof DashboardOrganiserTicketsRouteImport
      parentRoute: typeof DashboardOrganiserRoute
    }
    '/dashboard/organiser/settings': {
      id: '/dashboard/organiser/settings'
      path: '/settings'
      fullPath: '/dashboard/organiser/settings'
      preLoaderRoute: typeof DashboardOrganiserSettingsRouteImport
      parentRoute: typeof DashboardOrganiserRoute
    }
    '/dashboard/organiser/sales': {
      id: '/dashboard/organiser/sales'
      path: '/sales'
      fullPath: '/dashboard/organiser/sales'
      preLoaderRoute: typeof DashboardOrganiserSalesRouteImport
      parentRoute: typeof DashboardOrganiserRoute
    }
    '/dashboard/organiser/events': {
      id: '/dashboard/organiser/events'
      path: '/events'
      fullPath: '/dashboard/organiser/events'
      preLoaderRoute: typeof DashboardOrganiserEventsRouteImport
      parentRoute: typeof DashboardOrganiserRoute
    }
    '/dashboard/organiser/create-event': {
      id: '/dashboard/organiser/create-event'
      path: '/create-event'
      fullPath: '/dashboard/organiser/create-event'
      preLoaderRoute: typeof DashboardOrganiserCreateEventRouteImport
      parentRoute: typeof DashboardOrganiserRoute
    }
    '/dashboard/attendee/tickets': {
      id: '/dashboard/attendee/tickets'
      path: '/tickets'
      fullPath: '/dashboard/attendee/tickets'
      preLoaderRoute: typeof DashboardAttendeeTicketsRouteImport
      parentRoute: typeof DashboardAttendeeRoute
    }
    '/dashboard/attendee/settings': {
      id: '/dashboard/attendee/settings'
      path: '/settings'
      fullPath: '/dashboard/attendee/settings'
      preLoaderRoute: typeof DashboardAttendeeSettingsRouteImport
      parentRoute: typeof DashboardAttendeeRoute
    }
    '/dashboard/attendee/saved': {
      id: '/dashboard/attendee/saved'
      path: '/saved'
      fullPath: '/dashboard/attendee/saved'
      preLoaderRoute: typeof DashboardAttendeeSavedRouteImport
      parentRoute: typeof DashboardAttendeeRoute
    }
    '/dashboard/admin/tickets': {
      id: '/dashboard/admin/tickets'
      path: '/tickets'
      fullPath: '/dashboard/admin/tickets'
      preLoaderRoute: typeof DashboardAdminTicketsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/organiser/scan/$eventId': {
      id: '/dashboard/organiser/scan/$eventId'
      path: '/scan/$eventId'
      fullPath: '/dashboard/organiser/scan/$eventId'
      preLoaderRoute: typeof DashboardOrganiserScanEventIdRouteImport
      parentRoute: typeof DashboardOrganiserRoute
    }
    '/dashboard/organiser/edit-event/$eventId': {
      id: '/dashboard/organiser/edit-event/$eventId'
      path: '/edit-event/$eventId'
      fullPath: '/dashboard/organiser/edit-event/$eventId'
      preLoaderRoute: typeof DashboardOrganiserEditEventEventIdRouteImport
      parentRoute: typeof DashboardOrganiserRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminTicketsRoute: typeof DashboardAdminTicketsRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminTicketsRoute: DashboardAdminTicketsRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardAttendeeRouteChildren {
  DashboardAttendeeSavedRoute: typeof DashboardAttendeeSavedRoute
  DashboardAttendeeSettingsRoute: typeof DashboardAttendeeSettingsRoute
  DashboardAttendeeTicketsRoute: typeof DashboardAttendeeTicketsRoute
  DashboardAttendeeIndexRoute: typeof DashboardAttendeeIndexRoute
}

const DashboardAttendeeRouteChildren: DashboardAttendeeRouteChildren = {
  DashboardAttendeeSavedRoute: DashboardAttendeeSavedRoute,
  DashboardAttendeeSettingsRoute: DashboardAttendeeSettingsRoute,
  DashboardAttendeeTicketsRoute: DashboardAttendeeTicketsRoute,
  DashboardAttendeeIndexRoute: DashboardAttendeeIndexRoute,
}

const DashboardAttendeeRouteWithChildren =
  DashboardAttendeeRoute._addFileChildren(DashboardAttendeeRouteChildren)

interface DashboardOrganiserRouteChildren {
  DashboardOrganiserCreateEventRoute: typeof DashboardOrganiserCreateEventRoute
  DashboardOrganiserEventsRoute: typeof DashboardOrganiserEventsRoute
  DashboardOrganiserSalesRoute: typeof DashboardOrganiserSalesRoute
  DashboardOrganiserSettingsRoute: typeof DashboardOrganiserSettingsRoute
  DashboardOrganiserTicketsRoute: typeof DashboardOrganiserTicketsRoute
  DashboardOrganiserIndexRoute: typeof DashboardOrganiserIndexRoute
  DashboardOrganiserEditEventEventIdRoute: typeof DashboardOrganiserEditEventEventIdRoute
  DashboardOrganiserScanEventIdRoute: typeof DashboardOrganiserScanEventIdRoute
}

const DashboardOrganiserRouteChildren: DashboardOrganiserRouteChildren = {
  DashboardOrganiserCreateEventRoute: DashboardOrganiserCreateEventRoute,
  DashboardOrganiserEventsRoute: DashboardOrganiserEventsRoute,
  DashboardOrganiserSalesRoute: DashboardOrganiserSalesRoute,
  DashboardOrganiserSettingsRoute: DashboardOrganiserSettingsRoute,
  DashboardOrganiserTicketsRoute: DashboardOrganiserTicketsRoute,
  DashboardOrganiserIndexRoute: DashboardOrganiserIndexRoute,
  DashboardOrganiserEditEventEventIdRoute:
    DashboardOrganiserEditEventEventIdRoute,
  DashboardOrganiserScanEventIdRoute: DashboardOrganiserScanEventIdRoute,
}

const DashboardOrganiserRouteWithChildren =
  DashboardOrganiserRoute._addFileChildren(DashboardOrganiserRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardAttendeeRoute: typeof DashboardAttendeeRouteWithChildren
  DashboardOrganiserRoute: typeof DashboardOrganiserRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardAttendeeRoute: DashboardAttendeeRouteWithChildren,
  DashboardOrganiserRoute: DashboardOrganiserRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  OrderConfirmationOrderIdRoute: OrderConfirmationOrderIdRoute,
  OrganisersUsernameRoute: OrganisersUsernameRoute,
  EventsIndexRoute: EventsIndexRoute,
  EventsSlugCheckoutRoute: EventsSlugCheckoutRoute,
  EventsSlugIndexRoute: EventsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
